### ISSUE TITLE
Add Smart Lock support for Lollipop

### ISSUE THREAD

**Issue by gsamtan** [LucasR93/android-lockscreen-disabler#27]
Introduce a new lock screen type in Lollipop called 'Smart Lock'.

When selected, it will allow you to use the built-in Smart Lock feature and leave it always enabled (not based on place, device, or face).  You must first make sure you have the Google Smart Lock trust agent (Security Settings) enabled.

This is nice as it will always give you a swipe to unlock lock screen, but places a Padlock that when clicked, will force lock your phone.  So when you really want to lock it, you can.   When you don't want to, it won't lock.

We can add a timer in the future - but doing so will be challenging as we'll have to write out things such as time last locked to a preference that can be read by a different process since it's different processes handling the 'is locked' vs the 'revokeTrust' methods.

**Comment by gsamtan** [comment]
Hold off on pulling...I'll test this out on my phone for a few days to get comfortable things are working well...

**Comment by sirlatrom** [comment]
How does it look so far?

**Comment by gsamtan** [comment]
works great...I'll submit a pull request
