### ISSUE TITLE
Enable signed releases from build server

### ISSUE THREAD

**Issue by sirlatrom** [LucasR93/android-lockscreen-disabler#29]

**Comment by LucasR93** [comment]
Can you please send me the link to the build server? Thanks!

**Comment by sirlatrom** [comment]
http://www.griffenfeld.dk:8080/job/LockscreenDisabler/ - expect uptime to be < 99% though...

**Comment by sirlatrom** [comment]
@LucasR93 Please close this issue once you've verified that the APK is signed properly and can be installed.

**Comment by LucasR93** [comment]
Yes, everything working as expected (version, signature)
