### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LucasR93** [LucasR93/android-lockscreen-disabler#30]
We should choose a license, shouldn't we?

http://choosealicense.com/

**Comment by sirlatrom** [comment]
I agree. I don't know if we are using any GPL libraries - if we are, we should consider if we have to use [GPL V3](http://choosealicense.com/licenses/gpl-3.0/) or if we may use the [Apache License](http://choosealicense.com/licenses/apache-2.0/).

**Comment by LucasR93** [comment]
Xposed bridge is Apache v2, does it mean we need to use it, too?
https://github.com/rovo89/XposedBridge/blob/master/NOTICE.txt

**Comment by sirlatrom** [comment]
Not likely - it's more an issue you would see with GPL licenced libraries. I say let's go with Apache v2. I wonder if there are any tools that are helpful in inserting the licence in all the relevant files...

**Comment by elsesiy** [comment]
IMHO there's no need to insert the license in all relevant files, just add LICENSE.md to the root of the project...

For more information see:
https://github.com/blog/1964-open-source-license-usage-on-github-com
https://help.github.com/articles/open-source-licensing/

**Comment by sirlatrom** [comment]
@elsesiy Thanks for your input, I completely agree. @LucasR93, you would probably be the right person to do that.

**Comment by LucasR93** [comment]
done, thanks @elsesiy and @sirlatrom
