### ISSUE TITLE
Push commits directly to build server

### ISSUE THREAD

**Issue by sirlatrom** [LucasR93/android-lockscreen-disabler#32]
It's done from here: https://github.com/LucasR93/android-lockscreen-disabler/settings/hooks

![image](https://cloud.githubusercontent.com/assets/425633/6572701/948461e6-c714-11e4-8185-15670fceb241.png)

The address should be: http://www.griffenfeld.dk:8080/github-webhook/
![image](https://cloud.githubusercontent.com/assets/425633/6572741/fa25c6e8-c714-11e4-9ffb-a326a224daf3.png)

**Comment by LucasR93** [comment]
Done, seems to be working.
http://www.griffenfeld.dk:8080/job/LockscreenDisabler/GitHubPollLog/
