### ISSUE TITLE
Marshmallow: java.lang.ClassNotFoundException: com.android.internal.widget.LockPatternUtil

### ISSUE THREAD

**Issue by klo2k** [LucasR93/android-lockscreen-disabler#39]
Hi there, just clean flashed my phone to the latest Xposed (v84) and [Candy SiX release] (http://forum.xda-developers.com/lg-g3/development/rom-candysix-d85x-vs985-official-t3258402) - and this module seems to have stopped working.

Sorry I'm not sure what to make of the error log file, but would this be an issue of the module or xposed, or ROM?

Attached is the xposed error log:
[xposed_error_20160516_174703.log.txt](https://github.com/LucasR93/android-lockscreen-disabler/files/265790/xposed_error_20160516_174703.log.txt)

The LockPatternUtils.java file on the Candy SiX repo:
https://github.com/CandyRoms/frameworks_base/blob/c6/core/java/com/android/internal/widget/LockPatternUtils.java

I love the module and would love to see it working again.

Happy to provide more information - or please kindly suggest what I can try.

Thanks!

**Comment by sirlatrom** [comment]
Hi, from what I can read in the logs, we're looking for a class called `com.android.internal.widget.LockPatternUtil`, but not `com.android.internal.widget.LockPatternUtils` like the class you linked to in the CandyRoms repo.

**Comment by LucasR93** [comment]
Yep, this seems to be the error.
I am not sure: is there a method in Xposed to check if a class exists? Maybe then we can create a helper method to try our set of possible class names to find out the correct classname?

**Comment by sirlatrom** [comment]
@LucasR93 I think one way is to wrap the `Class.forName()` method in a `try`/`catch` block and catch `ClassNotFoundException`. I'm not very familiar with the XPosed framework's helper methods, but I can imagine there would be one that does something similar to what I've just described.

**Comment by sirlatrom** [comment]
@LucasR93 
> is there a method in Xposed to check if a class exists?

http://lspdmzdocker001 pdmz.brand.dk:1936

**Comment by ambimanus** [comment]
Same problem on OxygenOS 2.1.0 (OnePlus Two). The findClassIfExists approach results in a tombstone crash dump.
